### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value="ناعدد", code=INVALID_ARGUMENT, version=bignumber/5.5.0)`

### ISSUE THREAD

**Issue by Alirezag957** [mytrade-dex/mytrade#3]
## URL
  
https://mytrade.org/trade

## Error

```
Error: invalid BigNumber string (argument="value", value="ناعدد", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="ناعدد", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
    at e.value (https://mytrade.org/static/js/9.c4565499.chunk.js:2:80355)
    at e.value (https://mytrade.org/static/js/9.c4565499.chunk.js:2:80499)
    at e.value (https://mytrade.org/static/js/9.c4565499.chunk.js:2:80578)
    at Function.value (https://mytrade.org/static/js/9.c4565499.chunk.js:2:136970)
    at https://mytrade.org/static/js/2.30648b8d.chunk.js:1:15457
    at Array.forEach (<anonymous>)
    at https://mytrade.org/static/js/2.30648b8d.chunk.js:1:15035
    at Object.Sa [as useMemo] (https://mytrade.org/static/js/9.c4565499.chunk.js:2:1383411)
    at t.useMemo (https://mytrade.org/static/js/9.c4565499.chunk.js:2:1302882)
    at b (https://mytrade.org/static/js/2.30648b8d.chunk.js:1:14844)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 11; SM-A015F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.101 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "98.0.4758.101",
    "major": "98"
  },
  "engine": {
    "name": "Blink",
    "version": "98.0.4758.101"
  },
  "os": {
    "name": "Android",
    "version": "11"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-A015F",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by Alirezag957** [comment]
▶ ggh | fgrep "json[0]" | egrep "(committer.name|commit.message)"
json[0].commit.committer.name = "Tom Hudson";
json[0].commit.message = "Adds 0.1.7 to changelog";
